name: CI/CD for Next.js with Vercel

on:
  push:
    branches:
      - main  # Executar o workflow ao fazer push na branch main
  pull_request:
    branches:
      - main  # Opcional: Executar em pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Versão do Node.js
          cache: 'yarn'

      - name: Instalar dependências
        run: yarn install

      - name: Build do Next.js
        run: yarn build

      - name: Verificar código com ESLint # Opcional
        run: yarn lint

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Só roda se o job 'build' passar
    environment: PORTFOLIO

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Verificar Secrets
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "ERRO: VERCEL_TOKEN não está definido nos secrets do GitHub!"
            exit 1
          fi

      - name: Debug Environment Variables
        run: |
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy para Vercel com Logs Detalhados
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Token armazenado nos secrets do GitHub
        run: |
          echo "Iniciando deploy para Vercel..."
          npx vercel --prod --yes --debug --token "$VERCEL_TOKEN"
